# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YOLOSHOWUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1433, 827)
        mainWindow.setStyleSheet("QWidget#mainWindow{\n"
"    border: 1px solid rgba(0, 0, 0, 40%);\n"
"    border-top:none;\n"
"    border-bottom:none;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(mainWindow)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainBody = QtWidgets.QFrame(mainWindow)
        self.mainBody.setStyleSheet("QFrame#mainBody{\n"
"    border: 0px solid rgba(0, 0, 0, 40%);\n"
"    border-bottom:none;\n"
"    border-bottom-left-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"    border-radius:30%;\n"
"/*    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #B5FFFC, stop:0.2 #e0c3fc, stop:1 #FFDEE9);\n"
"*/\n"
"    background-color:white;\n"
"}")
        self.mainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.topbox = DoubleClickQFrame(self.mainBody)
        self.topbox.setStyleSheet("")
        self.topbox.setObjectName("topbox")
        self.topBox = QtWidgets.QHBoxLayout(self.topbox)
        self.topBox.setContentsMargins(0, 8, 0, 8)
        self.topBox.setSpacing(0)
        self.topBox.setObjectName("topBox")
        self.left_top = QtWidgets.QFrame(self.topbox)
        self.left_top.setMaximumSize(QtCore.QSize(150, 16777215))
        self.left_top.setStyleSheet("/* QFrame#left_top{\n"
"    border: 1px solid red;\n"
"} */\n"
"QPushButton#closeButton {\n"
"    background-color: rgb(255, 59, 48); /* 红色 */\n"
"    border: none;\n"
"    border-radius: 10px; /* 使按钮圆形 */\n"
"    min-width: 20px;\n"
"    max-width: 20px;\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"}\n"
"\n"
"QPushButton#maximizeButton {\n"
"    background-color: rgb(255, 214, 10); /* 黄色 */\n"
"    border: none;\n"
"    border-radius: 10px; /* 使按钮圆形 */\n"
"    min-width: 20px;\n"
"    max-width: 20px;\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"}\n"
"\n"
"QPushButton#minimizeButton {\n"
"    background-color: rgb(40, 205, 65); /* 绿色 */\n"
"    border: none;\n"
"    border-radius: 10px; /* 使按钮圆形 */\n"
"    min-width: 20px;\n"
"    max-width: 20px;\n"
"    min-height: 20px;\n"
"    max-height: 20px;\n"
"}\n"
"")
        self.left_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_top.setObjectName("left_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.left_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.closeButton = QtWidgets.QPushButton(self.left_top)
        self.closeButton.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(139, 29, 31);\n"
"    border-image: url(:/leftbox/images/newsize/close.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}")
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.maximizeButton = QtWidgets.QPushButton(self.left_top)
        self.maximizeButton.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(139, 29, 31);\n"
"    border-image: url(:/leftbox/images/newsize/max.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 214, 5);\n"
"}\n"
"\n"
"")
        self.maximizeButton.setText("")
        self.maximizeButton.setObjectName("maximizeButton")
        self.horizontalLayout_2.addWidget(self.maximizeButton)
        self.minimizeButton = QtWidgets.QPushButton(self.left_top)
        self.minimizeButton.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(139, 29, 31);\n"
"    border-image: url(:/leftbox/images/newsize/min.png);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 205, 60);\n"
"}")
        self.minimizeButton.setText("")
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_2.addWidget(self.minimizeButton)
        self.topBox.addWidget(self.left_top)
        self.right_top = QtWidgets.QFrame(self.topbox)
        self.right_top.setStyleSheet("QLabel#title{\n"
"    background-color: none;\n"
"    font-size: 22px;\n"
"    font-family: \"Shojumaru\";\n"
"}\n"
"Spacer{\n"
"    border:none;\n"
"}")
        self.right_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_top.setObjectName("right_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.right_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QLabel(self.right_top)
        font = QtGui.QFont()
        font.setFamily("Shojumaru")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        self.title.setFont(font)
        self.title.setStyleSheet("")
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title, 0, QtCore.Qt.AlignHCenter)
        self.topBox.addWidget(self.right_top, 0, QtCore.Qt.AlignHCenter)
        self.topBox.setStretch(0, 1)
        self.topBox.setStretch(1, 9)
        self.verticalLayout_4.addWidget(self.topbox)
        self.mainbox = QtWidgets.QFrame(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainbox.sizePolicy().hasHeightForWidth())
        self.mainbox.setSizePolicy(sizePolicy)
        self.mainbox.setStyleSheet("QFrame#mainbox{\n"
"    border: 1px solid rgba(0, 0, 0, 15%);\n"
"   /*\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #B5FFFC, stop:0.2 #e0c3fc, stop:1 #FFDEE9);\n"
"     */\n"
"    border-bottom-left-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"    border-radius:30%;\n"
"}\n"
"")
        self.mainbox.setObjectName("mainbox")
        self.mainBox = QtWidgets.QHBoxLayout(self.mainbox)
        self.mainBox.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.mainBox.setContentsMargins(0, 0, 0, 0)
        self.mainBox.setSpacing(0)
        self.mainBox.setObjectName("mainBox")
        self.leftBox = QtWidgets.QFrame(self.mainbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setMinimumSize(QtCore.QSize(80, 0))
        self.leftBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leftBox.setStyleSheet("QFrame#leftBox  {\n"
"    /*background-color: rgba(255, 255, 255, 80%);*/\n"
"    border: 0px solid rgba(0, 0, 0, 40%);\n"
"    border-top:none;\n"
"    border-bottom:none;\n"
"    border-left:none;\n"
"}\n"
"")
        self.leftBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.leftbox_top = QtWidgets.QFrame(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftbox_top.sizePolicy().hasHeightForWidth())
        self.leftbox_top.setSizePolicy(sizePolicy)
        self.leftbox_top.setMinimumSize(QtCore.QSize(180, 0))
        self.leftbox_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftbox_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftbox_top.setObjectName("leftbox_top")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.leftbox_top)
        self.horizontalLayout_8.setContentsMargins(10, 10, 15, 3)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.logo = QtWidgets.QFrame(self.leftbox_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setStyleSheet("image: url(:/leftbox/images/swimmingliu_icon.png);\n"
"border:2px solid rgba(0,0,0,5%);\n"
"border-radius: 10%;\n"
"")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.horizontalLayout_8.addWidget(self.logo)
        self.top_intro = QtWidgets.QFrame(self.leftbox_top)
        self.top_intro.setStyleSheet("QLabel{\n"
"    color: black;\n"
"    font: 600 italic 9pt \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"QFrame{\n"
"    border:none;\n"
"}")
        self.top_intro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_intro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_intro.setObjectName("top_intro")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.top_intro)
        self.verticalLayout_20.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label = QtWidgets.QLabel(self.top_intro)
        self.label.setObjectName("label")
        self.verticalLayout_20.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.top_intro)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_20.addWidget(self.label_3)
        self.horizontalLayout_8.addWidget(self.top_intro)
        self.horizontalLayout_8.setStretch(0, 4)
        self.horizontalLayout_8.setStretch(1, 6)
        self.verticalLayout_2.addWidget(self.leftbox_top)
        self.leftbox_bottom = QtWidgets.QFrame(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftbox_bottom.sizePolicy().hasHeightForWidth())
        self.leftbox_bottom.setSizePolicy(sizePolicy)
        self.leftbox_bottom.setMinimumSize(QtCore.QSize(0, 0))
        self.leftbox_bottom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftbox_bottom.setStyleSheet("QPushButton#src_menu{\n"
"    background-image: url(:/leftbox/images/newsize/menu.png);\n"
"}\n"
"QPushButton#src_folder{\n"
"    background-image: url(:/leftbox/images/newsize/folder.png);\n"
"\n"
"}\n"
"QPushButton#src_camera{\n"
"    background-image: url(:/leftbox/images/newsize/security-camera.png);\n"
"}\n"
"QPushButton#src_img{\n"
"    background-image: url(:/leftbox/images/newsize/gallery.png);\n"
"}\n"
"QPushButton#src_webcam{\n"
"    background-image: url(:/leftbox/images/newsize/photo-camera.png);\n"
"}\n"
"QPushButton#src_setting{\n"
"    background-image:url(:/leftbox/images/newsize/setting.png);\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    text-align: center;\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    border-left: 23px solid transparent;\n"
"    color: rgba(0, 0, 0, 199);\n"
"    font: 12pt \"Times New Roman\";\n"
"    font-weight: bold;\n"
"    padding-left: 15px;\n"
"}\n"
"QFrame#cameraBox:hover{\n"
"    background-color: rgba(114, 129, 214, 59);\n"
"}\n"
"QFrame#folderBox:hover{\n"
"    background-color: rgba(114, 129, 214, 59);\n"
"}\n"
"QFrame#imgBox:hover{\n"
"    background-color: rgba(114, 129, 214, 59);\n"
"}\n"
"QFrame#menuBox:hover{\n"
"    background-color: rgba(114, 129, 214, 59);\n"
"}\n"
"QFrame#webcamBox:hover{\n"
"    background-color: rgba(114, 129, 214, 59);\n"
"}\n"
"QFrame#manageBox:hover{\n"
"    background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.leftbox_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftbox_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftbox_bottom.setObjectName("leftbox_bottom")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftbox_bottom)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.menuBox = QtWidgets.QFrame(self.leftbox_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBox.sizePolicy().hasHeightForWidth())
        self.menuBox.setSizePolicy(sizePolicy)
        self.menuBox.setMinimumSize(QtCore.QSize(180, 0))
        self.menuBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.menuBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuBox.setObjectName("menuBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menuBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.src_menu = QtWidgets.QPushButton(self.menuBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.src_menu.sizePolicy().hasHeightForWidth())
        self.src_menu.setSizePolicy(sizePolicy)
        self.src_menu.setMinimumSize(QtCore.QSize(180, 0))
        self.src_menu.setMaximumSize(QtCore.QSize(180, 16777215))
        self.src_menu.setIconSize(QtCore.QSize(30, 30))
        self.src_menu.setAutoDefault(False)
        self.src_menu.setObjectName("src_menu")
        self.horizontalLayout_3.addWidget(self.src_menu)
        self.verticalLayout_3.addWidget(self.menuBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.imgBox = QtWidgets.QFrame(self.leftbox_bottom)
        self.imgBox.setMinimumSize(QtCore.QSize(180, 0))
        self.imgBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.imgBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.imgBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgBox.setObjectName("imgBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.imgBox)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.src_img = QtWidgets.QPushButton(self.imgBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.src_img.sizePolicy().hasHeightForWidth())
        self.src_img.setSizePolicy(sizePolicy)
        self.src_img.setMinimumSize(QtCore.QSize(180, 0))
        self.src_img.setMaximumSize(QtCore.QSize(180, 16777215))
        self.src_img.setIconSize(QtCore.QSize(30, 30))
        self.src_img.setObjectName("src_img")
        self.horizontalLayout_4.addWidget(self.src_img, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addWidget(self.imgBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.webcamBox = QtWidgets.QFrame(self.leftbox_bottom)
        self.webcamBox.setMinimumSize(QtCore.QSize(180, 0))
        self.webcamBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.webcamBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.webcamBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.webcamBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.webcamBox.setObjectName("webcamBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.webcamBox)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.src_webcam = QtWidgets.QPushButton(self.webcamBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.src_webcam.sizePolicy().hasHeightForWidth())
        self.src_webcam.setSizePolicy(sizePolicy)
        self.src_webcam.setMinimumSize(QtCore.QSize(180, 0))
        self.src_webcam.setMaximumSize(QtCore.QSize(180, 16777215))
        self.src_webcam.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.src_webcam.setIconSize(QtCore.QSize(30, 30))
        self.src_webcam.setObjectName("src_webcam")
        self.horizontalLayout_7.addWidget(self.src_webcam, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addWidget(self.webcamBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.folderBox = QtWidgets.QFrame(self.leftbox_bottom)
        self.folderBox.setMinimumSize(QtCore.QSize(180, 0))
        self.folderBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.folderBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.folderBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.folderBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.folderBox.setObjectName("folderBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.folderBox)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.src_folder = QtWidgets.QPushButton(self.folderBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.src_folder.sizePolicy().hasHeightForWidth())
        self.src_folder.setSizePolicy(sizePolicy)
        self.src_folder.setMinimumSize(QtCore.QSize(180, 0))
        self.src_folder.setMaximumSize(QtCore.QSize(180, 16777215))
        self.src_folder.setIconSize(QtCore.QSize(30, 30))
        self.src_folder.setObjectName("src_folder")
        self.horizontalLayout_6.addWidget(self.src_folder, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addWidget(self.folderBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.cameraBox = QtWidgets.QFrame(self.leftbox_bottom)
        self.cameraBox.setMinimumSize(QtCore.QSize(180, 0))
        self.cameraBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.cameraBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cameraBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cameraBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraBox.setObjectName("cameraBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.cameraBox)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.src_camera = QtWidgets.QPushButton(self.cameraBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.src_camera.sizePolicy().hasHeightForWidth())
        self.src_camera.setSizePolicy(sizePolicy)
        self.src_camera.setMinimumSize(QtCore.QSize(180, 0))
        self.src_camera.setMaximumSize(QtCore.QSize(180, 16777215))
        self.src_camera.setIconSize(QtCore.QSize(30, 30))
        self.src_camera.setObjectName("src_camera")
        self.horizontalLayout_5.addWidget(self.src_camera, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addWidget(self.cameraBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.manageBox = QtWidgets.QFrame(self.leftbox_bottom)
        self.manageBox.setMinimumSize(QtCore.QSize(180, 0))
        self.manageBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.manageBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manageBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manageBox.setObjectName("manageBox")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.manageBox)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.src_setting = QtWidgets.QPushButton(self.manageBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.src_setting.sizePolicy().hasHeightForWidth())
        self.src_setting.setSizePolicy(sizePolicy)
        self.src_setting.setMinimumSize(QtCore.QSize(180, 0))
        self.src_setting.setMaximumSize(QtCore.QSize(180, 16777215))
        self.src_setting.setObjectName("src_setting")
        self.horizontalLayout_19.addWidget(self.src_setting)
        self.verticalLayout_3.addWidget(self.manageBox)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 4)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 4)
        self.verticalLayout_3.setStretch(4, 1)
        self.verticalLayout_3.setStretch(5, 4)
        self.verticalLayout_3.setStretch(6, 1)
        self.verticalLayout_3.setStretch(7, 4)
        self.verticalLayout_3.setStretch(8, 1)
        self.verticalLayout_3.setStretch(9, 4)
        self.verticalLayout_3.setStretch(10, 1)
        self.verticalLayout_3.setStretch(11, 4)
        self.verticalLayout_2.addWidget(self.leftbox_bottom)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 55)
        self.verticalLayout_2.setStretch(2, 35)
        self.mainBox.addWidget(self.leftBox)
        self.rightBox = QtWidgets.QFrame(self.mainbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightBox.sizePolicy().hasHeightForWidth())
        self.rightBox.setSizePolicy(sizePolicy)
        self.rightBox.setMinimumSize(QtCore.QSize(0, 0))
        self.rightBox.setStyleSheet("QFrame#rightBox{\n"
"    margin-top: -1px;\n"
"    margin-right: -1px;\n"
"    margin-bottom: -1px;\n"
"    background-color:  #fffff;\n"
"    border: 1px solid rgba(0, 0, 0, 15%);\n"
"    border-radius: 30%;\n"
"    background-color: rgb(245, 249, 254);\n"
"}\n"
"QFrame#rightbox_top{\n"
"    border:2px solid rgb(255, 255, 255);\n"
"    border-radius:15%;\n"
"    background-color: rgb(238, 242, 255);\n"
"}\n"
"\n"
"QFrame#main_leftbox{\n"
"    border:2px solid rgb(255, 255, 255);\n"
"    border-radius:15%;\n"
"    background-color: rgb(238, 242, 255);\n"
"}\n"
"QFrame#main_rightbox{\n"
"    border:2px solid rgb(255, 255, 255);\n"
"    border-radius:15%;\n"
"    background-color: rgb(238, 242, 255);\n"
"}\n"
"/*QFrame#rightbox_bottom{\n"
"    border:2px solid rgb(255, 255, 255);\n"
"    border-radius:10%;\n"
"}*/")
        self.rightBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightBox.setObjectName("rightBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.rightBox)
        self.verticalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rightbox_top = QtWidgets.QFrame(self.rightBox)
        self.rightbox_top.setStyleSheet("")
        self.rightbox_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightbox_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightbox_top.setObjectName("rightbox_top")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.rightbox_top)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_6 = QtWidgets.QFrame(self.rightbox_top)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_22.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.classesLabel = QtWidgets.QLabel(self.frame_6)
        self.classesLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.classesLabel.setText("")
        self.classesLabel.setPixmap(QtGui.QPixmap(":/statusbar/images/newsize/classesBar.png"))
        self.classesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.classesLabel.setObjectName("classesLabel")
        self.horizontalLayout_22.addWidget(self.classesLabel)
        self.Class_QF = QtWidgets.QFrame(self.frame_6)
        self.Class_QF.setMinimumSize(QtCore.QSize(170, 80))
        self.Class_QF.setMaximumSize(QtCore.QSize(170, 80))
        self.Class_QF.setToolTipDuration(0)
        self.Class_QF.setStyleSheet("QFrame#Class_QF{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color:qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0  #97D9E1,  stop:1   #8EC5FC);\n"
"border: 1px outset #97D9E1;\n"
"}\n"
"")
        self.Class_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Class_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Class_QF.setObjectName("Class_QF")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Class_QF)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Class_top = QtWidgets.QFrame(self.Class_QF)
        self.Class_top.setStyleSheet("border:none")
        self.Class_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Class_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Class_top.setObjectName("Class_top")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.Class_top)
        self.horizontalLayout_11.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.Class_top)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(255, 255,255, 210);\n"
"text-align:center;\n"
"font: 700 italic 16pt \"Segoe UI\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.verticalLayout_7.addWidget(self.Class_top)
        self.line_2 = QtWidgets.QFrame(self.Class_QF)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.Class_bottom = QtWidgets.QFrame(self.Class_QF)
        self.Class_bottom.setStyleSheet("border:none")
        self.Class_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Class_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Class_bottom.setObjectName("Class_bottom")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Class_bottom)
        self.verticalLayout_8.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Class_num = QtWidgets.QLabel(self.Class_bottom)
        self.Class_num.setMinimumSize(QtCore.QSize(0, 30))
        self.Class_num.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.Class_num.setFont(font)
        self.Class_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 17pt \"Microsoft YaHei UI\";")
        self.Class_num.setText("")
        self.Class_num.setAlignment(QtCore.Qt.AlignCenter)
        self.Class_num.setObjectName("Class_num")
        self.verticalLayout_8.addWidget(self.Class_num, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.Class_bottom)
        self.verticalLayout_7.setStretch(1, 2)
        self.verticalLayout_7.setStretch(2, 1)
        self.horizontalLayout_22.addWidget(self.Class_QF)
        self.horizontalLayout_14.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.rightbox_top)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_23.setContentsMargins(0, 9, 9, 9)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.targetLabel = QtWidgets.QLabel(self.frame_7)
        self.targetLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.targetLabel.setText("")
        self.targetLabel.setPixmap(QtGui.QPixmap(":/statusbar/images/newsize/targetBar.png"))
        self.targetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.targetLabel.setObjectName("targetLabel")
        self.horizontalLayout_23.addWidget(self.targetLabel)
        self.Target_QF = QtWidgets.QFrame(self.frame_7)
        self.Target_QF.setMinimumSize(QtCore.QSize(170, 80))
        self.Target_QF.setMaximumSize(QtCore.QSize(170, 80))
        self.Target_QF.setToolTipDuration(0)
        self.Target_QF.setStyleSheet("QFrame#Target_QF{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 #E0C3FC,  stop:1  #9599E2);\n"
"border: 1px outset #9599E2;\n"
"}\n"
"")
        self.Target_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Target_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Target_QF.setObjectName("Target_QF")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Target_QF)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Target_top = QtWidgets.QFrame(self.Target_QF)
        self.Target_top.setStyleSheet("border:none")
        self.Target_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Target_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Target_top.setObjectName("Target_top")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Target_top)
        self.horizontalLayout_12.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.Target_top)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255, 255,255, 210);\n"
"text-align:center;\n"
"font: 700 italic 16pt \"Segoe UI\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.verticalLayout_9.addWidget(self.Target_top)
        self.line_3 = QtWidgets.QFrame(self.Target_QF)
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_9.addWidget(self.line_3)
        self.Target_bottom = QtWidgets.QFrame(self.Target_QF)
        self.Target_bottom.setStyleSheet("border:none")
        self.Target_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Target_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Target_bottom.setObjectName("Target_bottom")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Target_bottom)
        self.verticalLayout_10.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Target_num = QtWidgets.QLabel(self.Target_bottom)
        self.Target_num.setMinimumSize(QtCore.QSize(0, 30))
        self.Target_num.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.Target_num.setFont(font)
        self.Target_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 17pt \"Microsoft YaHei UI\";")
        self.Target_num.setText("")
        self.Target_num.setAlignment(QtCore.Qt.AlignCenter)
        self.Target_num.setObjectName("Target_num")
        self.verticalLayout_10.addWidget(self.Target_num, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_9.addWidget(self.Target_bottom)
        self.verticalLayout_9.setStretch(1, 2)
        self.verticalLayout_9.setStretch(2, 1)
        self.horizontalLayout_23.addWidget(self.Target_QF)
        self.horizontalLayout_14.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.rightbox_top)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_24.setContentsMargins(0, 9, 9, 9)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.fpsLabel = QtWidgets.QLabel(self.frame_8)
        self.fpsLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.fpsLabel.setText("")
        self.fpsLabel.setPixmap(QtGui.QPixmap(":/statusbar/images/newsize/fpsBar.png"))
        self.fpsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fpsLabel.setObjectName("fpsLabel")
        self.horizontalLayout_24.addWidget(self.fpsLabel)
        self.Fps_QF = QtWidgets.QFrame(self.frame_8)
        self.Fps_QF.setMinimumSize(QtCore.QSize(170, 80))
        self.Fps_QF.setMaximumSize(QtCore.QSize(170, 80))
        self.Fps_QF.setToolTipDuration(0)
        self.Fps_QF.setStyleSheet("QFrame#Fps_QF{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(243, 175, 189),  stop:1 rgb(155, 118, 218));\n"
"border: 1px outset rgb(153, 117, 219)\n"
"}\n"
"")
        self.Fps_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Fps_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Fps_QF.setObjectName("Fps_QF")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Fps_QF)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Fps_top = QtWidgets.QFrame(self.Fps_QF)
        self.Fps_top.setStyleSheet("border:none")
        self.Fps_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Fps_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Fps_top.setObjectName("Fps_top")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.Fps_top)
        self.horizontalLayout_10.setContentsMargins(0, 3, 7, 3)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.Fps_top)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgba(255, 255,255, 210);\n"
"text-align:center;\n"
"font: 700 italic 16pt \"Segoe UI\";")
        self.label_7.setMidLineWidth(-1)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setIndent(0)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.verticalLayout_11.addWidget(self.Fps_top)
        self.line_4 = QtWidgets.QFrame(self.Fps_QF)
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_4.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_11.addWidget(self.line_4)
        self.Fps_bottom = QtWidgets.QFrame(self.Fps_QF)
        self.Fps_bottom.setStyleSheet("border:none")
        self.Fps_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Fps_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Fps_bottom.setObjectName("Fps_bottom")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Fps_bottom)
        self.verticalLayout_12.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.fps_label = QtWidgets.QLabel(self.Fps_bottom)
        self.fps_label.setMinimumSize(QtCore.QSize(0, 30))
        self.fps_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.fps_label.setFont(font)
        self.fps_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 17pt \"Microsoft YaHei UI\";")
        self.fps_label.setText("")
        self.fps_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fps_label.setObjectName("fps_label")
        self.verticalLayout_12.addWidget(self.fps_label, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_11.addWidget(self.Fps_bottom)
        self.verticalLayout_11.setStretch(1, 2)
        self.verticalLayout_11.setStretch(2, 1)
        self.horizontalLayout_24.addWidget(self.Fps_QF)
        self.horizontalLayout_14.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.rightbox_top)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_25.setContentsMargins(0, 9, 9, 9)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.modelLabel = QtWidgets.QLabel(self.frame_9)
        self.modelLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.modelLabel.setText("")
        self.modelLabel.setPixmap(QtGui.QPixmap(":/statusbar/images/newsize/modelBar.png"))
        self.modelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.modelLabel.setObjectName("modelLabel")
        self.horizontalLayout_25.addWidget(self.modelLabel)
        self.Model_QF = QtWidgets.QFrame(self.frame_9)
        self.Model_QF.setMinimumSize(QtCore.QSize(170, 80))
        self.Model_QF.setMaximumSize(QtCore.QSize(170, 80))
        self.Model_QF.setToolTipDuration(0)
        self.Model_QF.setStyleSheet("QFrame#Model_QF{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(162, 129, 247),  stop:1 rgb(119, 111, 252));\n"
"border: 1px outset rgb(98, 91, 213);\n"
"}\n"
"")
        self.Model_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Model_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Model_QF.setObjectName("Model_QF")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Model_QF)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Model_top = QtWidgets.QFrame(self.Model_QF)
        self.Model_top.setStyleSheet("border:none")
        self.Model_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Model_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Model_top.setObjectName("Model_top")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.Model_top)
        self.horizontalLayout_13.setContentsMargins(0, 3, 7, 3)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.Model_top)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgba(255, 255,255, 210);\n"
"text-align:center;\n"
"font: 700 italic 16pt \"Segoe UI\";")
        self.label_8.setMidLineWidth(-1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setIndent(0)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.verticalLayout_13.addWidget(self.Model_top)
        self.line_5 = QtWidgets.QFrame(self.Model_QF)
        self.line_5.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_5.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_13.addWidget(self.line_5)
        self.Model_bottom = QtWidgets.QFrame(self.Model_QF)
        self.Model_bottom.setStyleSheet("border:none")
        self.Model_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Model_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Model_bottom.setObjectName("Model_bottom")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.Model_bottom)
        self.verticalLayout_14.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Model_label = QtWidgets.QLabel(self.Model_bottom)
        self.Model_label.setMinimumSize(QtCore.QSize(0, 30))
        self.Model_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.Model_label.setFont(font)
        self.Model_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Microsoft YaHei UI\";\n"
"")
        self.Model_label.setText("")
        self.Model_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Model_label.setObjectName("Model_label")
        self.verticalLayout_14.addWidget(self.Model_label, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_13.addWidget(self.Model_bottom)
        self.verticalLayout_13.setStretch(1, 2)
        self.verticalLayout_13.setStretch(2, 1)
        self.horizontalLayout_25.addWidget(self.Model_QF)
        self.horizontalLayout_14.addWidget(self.frame_9)
        self.verticalLayout_5.addWidget(self.rightbox_top)
        self.rightbox_main = QtWidgets.QFrame(self.rightBox)
        self.rightbox_main.setStyleSheet("")
        self.rightbox_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightbox_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightbox_main.setObjectName("rightbox_main")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.rightbox_main)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.splitter = QtWidgets.QSplitter(self.rightbox_main)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.main_leftbox = QtWidgets.QLabel(self.splitter)
        self.main_leftbox.setMinimumSize(QtCore.QSize(200, 100))
        self.main_leftbox.setText("")
        self.main_leftbox.setObjectName("main_leftbox")
        self.main_rightbox = QtWidgets.QLabel(self.splitter)
        self.main_rightbox.setMinimumSize(QtCore.QSize(200, 100))
        self.main_rightbox.setText("")
        self.main_rightbox.setObjectName("main_rightbox")
        self.horizontalLayout_9.addWidget(self.splitter)
        self.verticalLayout_5.addWidget(self.rightbox_main)
        self.rightbox_play = QtWidgets.QFrame(self.rightBox)
        self.rightbox_play.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightbox_play.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightbox_play.setObjectName("rightbox_play")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.rightbox_play)
        self.horizontalLayout_20.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.run_button = QtWidgets.QPushButton(self.rightbox_play)
        self.run_button.setMinimumSize(QtCore.QSize(0, 30))
        self.run_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.run_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_button.setMouseTracking(True)
        self.run_button.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"border: none;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.run_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rightbox/images/newsize/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_button.setIcon(icon)
        self.run_button.setIconSize(QtCore.QSize(20, 20))
        self.run_button.setCheckable(True)
        self.run_button.setChecked(False)
        self.run_button.setObjectName("run_button")
        self.horizontalLayout_20.addWidget(self.run_button)
        self.progress_bar = QtWidgets.QProgressBar(self.rightbox_play)
        self.progress_bar.setMinimumSize(QtCore.QSize(0, 20))
        self.progress_bar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progress_bar.setStyleSheet("QProgressBar{ \n"
"font: 700 10pt \"Nirmala UI\";\n"
"color: #8EC5FC; \n"
"text-align:center; \n"
"border:3px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"background-color: rgba(215, 215, 215,100);\n"
"} \n"
"\n"
"QProgressBar:chunk{ \n"
"border-radius:0px; \n"
"background:  lightgrey;\n"
"border-radius: 7px;\n"
"}")
        self.progress_bar.setMaximum(100)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout_20.addWidget(self.progress_bar)
        self.stop_button = QtWidgets.QPushButton(self.rightbox_play)
        self.stop_button.setMinimumSize(QtCore.QSize(0, 30))
        self.stop_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stop_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_button.setStyleSheet("QPushButton{\n"
"background-image: url(:/rightbox/images/newsize/stop.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.stop_button.setText("")
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_20.addWidget(self.stop_button)
        self.verticalLayout_5.addWidget(self.rightbox_play)
        self.rightbox_bottom = QtWidgets.QFrame(self.rightBox)
        self.rightbox_bottom.setStyleSheet("")
        self.rightbox_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightbox_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightbox_bottom.setObjectName("rightbox_bottom")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.rightbox_bottom)
        self.horizontalLayout_15.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.message_bar = QtWidgets.QLabel(self.rightbox_bottom)
        self.message_bar.setStyleSheet("font: 700 11pt \"Segoe UI\";\n"
"color: rgba(0, 0, 0, 140);")
        self.message_bar.setObjectName("message_bar")
        self.horizontalLayout_15.addWidget(self.message_bar)
        self.verticalLayout_5.addWidget(self.rightbox_bottom)
        self.verticalLayout_5.setStretch(0, 10)
        self.verticalLayout_5.setStretch(1, 86)
        self.verticalLayout_5.setStretch(3, 2)
        self.mainBox.addWidget(self.rightBox)
        self.settingBox = QtWidgets.QFrame(self.mainbox)
        self.settingBox.setMinimumSize(QtCore.QSize(0, 0))
        self.settingBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.settingBox.setStyleSheet("QFrame#settingBox{\n"
"    margin-top: -1px;\n"
"    margin-right: -1px;\n"
"    margin-bottom: -1px;\n"
"    background-color:  #fffff;\n"
"    border: 1px solid rgba(0, 0, 0, 15%);\n"
"    border-radius: 30%;\n"
"    border-top-left-radius: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    margin-left: 1px;\n"
"    border-left:none;\n"
"}")
        self.settingBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingBox.setObjectName("settingBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.settingBox)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.setting_page = QtWidgets.QFrame(self.settingBox)
        self.setting_page.setMinimumSize(QtCore.QSize(0, 0))
        self.setting_page.setMaximumSize(QtCore.QSize(220, 16777215))
        self.setting_page.setStyleSheet("QFrame#setting_page{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #8EC5FC, stop:1 #E0C3FC);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:30%;\n"
"    border-bottom-right-radius:30%;\n"
"    border-bottom-left-radius:0px;\n"
"    border:none;\n"
"}")
        self.setting_page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setting_page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_page.setObjectName("setting_page")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.setting_page)
        self.verticalLayout_22.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_22.setSpacing(15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_2 = QtWidgets.QLabel(self.setting_page)
        self.label_2.setStyleSheet("padding-left: 0px;\n"
"padding-bottom: 2px;\n"
"color: white;\n"
"font: 700 italic 16pt \"Segoe UI\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_22.addWidget(self.label_2)
        self.Model_QF_2 = QtWidgets.QWidget(self.setting_page)
        self.Model_QF_2.setMinimumSize(QtCore.QSize(190, 90))
        self.Model_QF_2.setMaximumSize(QtCore.QSize(190, 90))
        self.Model_QF_2.setStyleSheet("QWidget#Model_QF_2{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.Model_QF_2.setObjectName("Model_QF_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.Model_QF_2)
        self.verticalLayout_21.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.ToggleBotton_6 = QtWidgets.QPushButton(self.Model_QF_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton_6.sizePolicy().hasHeightForWidth())
        self.ToggleBotton_6.setSizePolicy(sizePolicy)
        self.ToggleBotton_6.setMinimumSize(QtCore.QSize(0, 30))
        self.ToggleBotton_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        self.ToggleBotton_6.setFont(font)
        self.ToggleBotton_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ToggleBotton_6.setMouseTracking(True)
        self.ToggleBotton_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton_6.setAutoFillBackground(False)
        self.ToggleBotton_6.setStyleSheet("QPushButton{\n"
"background-image: url(:/setting /images/newsize/model.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 20px solid transparent;\n"
"\n"
"text-align: left;\n"
"padding-left: 40px;\n"
"padding-bottom: 2px;\n"
"color: white;\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton_6.setIcon(icon)
        self.ToggleBotton_6.setAutoDefault(False)
        self.ToggleBotton_6.setDefault(False)
        self.ToggleBotton_6.setFlat(False)
        self.ToggleBotton_6.setObjectName("ToggleBotton_6")
        self.verticalLayout_21.addWidget(self.ToggleBotton_6)
        self.model_box = ComboBox(self.Model_QF_2)
        self.model_box.setMinimumSize(QtCore.QSize(170, 22))
        self.model_box.setMaximumSize(QtCore.QSize(170, 20))
        self.model_box.setStyleSheet("ComboBox {\n"
"            background-color: rgba(255,255,255,90);\n"
"            color: rgba(0, 0, 0, 200);\n"
"            border: 1px solid lightgray;\n"
"            border-radius: 10px;\n"
"            padding: 2px;\n"
"            text-align: left;\n"
"            font: 600 9pt \"Segoe UI\";\n"
"            padding-left: 15px;\n"
"}      \n"
"ComboBox:on {\n"
"            border: 1px solid #63acfb;       \n"
" }\n"
"\n"
"ComboBox::drop-down {\n"
"            width: 22px;\n"
"            border-left: 1px solid lightgray;\n"
"            border-top-right-radius: 15px;\n"
"            border-bottom-right-radius: 15px; \n"
"}\n"
"ComboBox::drop-down:on {\n"
"            border-left: 1px solid #63acfb;\n"
" }\n"
"\n"
"ComboBox::down-arrow {\n"
"            width: 16px;\n"
"            height: 16px;\n"
"            image: url(:/setting /images/newsize/box_down.png);\n"
" }\n"
"\n"
"ComboBox::down-arrow:on {\n"
"            image: url(:/setting /images/newsize/box_up.png);\n"
" }\n"
"")
        self.model_box.setProperty("minimumContentsLength", 0)
        self.model_box.setProperty("placeholderText", "")
        self.model_box.setObjectName("model_box")
        self.verticalLayout_21.addWidget(self.model_box)
        self.verticalLayout_22.addWidget(self.Model_QF_2)
        self.IOU_QF = QtWidgets.QFrame(self.setting_page)
        self.IOU_QF.setMinimumSize(QtCore.QSize(190, 90))
        self.IOU_QF.setMaximumSize(QtCore.QSize(190, 90))
        self.IOU_QF.setStyleSheet("QFrame#IOU_QF{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.IOU_QF.setObjectName("IOU_QF")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.IOU_QF)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.ToggleBotton_2 = QtWidgets.QPushButton(self.IOU_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton_2.sizePolicy().hasHeightForWidth())
        self.ToggleBotton_2.setSizePolicy(sizePolicy)
        self.ToggleBotton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.ToggleBotton_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        self.ToggleBotton_2.setFont(font)
        self.ToggleBotton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ToggleBotton_2.setMouseTracking(True)
        self.ToggleBotton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton_2.setAutoFillBackground(False)
        self.ToggleBotton_2.setStyleSheet("QPushButton{\n"
"background-image:url(:/setting /images/newsize/IOU.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 20px solid transparent;\n"
"\n"
"text-align: left;\n"
"padding-left: 40px;\n"
"padding-bottom: 4px;\n"
"color: white;\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton_2.setIcon(icon)
        self.ToggleBotton_2.setAutoDefault(False)
        self.ToggleBotton_2.setDefault(False)
        self.ToggleBotton_2.setFlat(False)
        self.ToggleBotton_2.setObjectName("ToggleBotton_2")
        self.verticalLayout_15.addWidget(self.ToggleBotton_2)
        self.frame_3 = QtWidgets.QFrame(self.IOU_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_16.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_16.setSpacing(10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.iou_spinbox = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.iou_spinbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iou_spinbox.setStyleSheet("QDoubleSpinBox {\n"
"border: 0px solid lightgray;\n"
"border-radius: 2px;\n"
"background-color: rgba(255,255,255,90);\n"
"font: 600 9pt \"Segoe UI\";\n"
"}\n"
"        \n"
"QDoubleSpinBox::up-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/setting /images/newsize/box_up.png);\n"
"}\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top: 1px;\n"
"}\n"
"            \n"
"QDoubleSpinBox::down-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image:url(:/setting /images/newsize/box_down.png);\n"
"}\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom: 1px;\n"
"}")
        self.iou_spinbox.setMinimum(0.01)
        self.iou_spinbox.setMaximum(1.0)
        self.iou_spinbox.setSingleStep(0.05)
        self.iou_spinbox.setProperty("value", 0.45)
        self.iou_spinbox.setObjectName("iou_spinbox")
        self.horizontalLayout_16.addWidget(self.iou_spinbox)
        self.iou_slider = QtWidgets.QSlider(self.frame_3)
        self.iou_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iou_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: none;\n"
"height: 10px;\n"
"background-color: rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 10px;\n"
"margin: -1px 0px -1px 0px;\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #59969b, stop:1 #04e7fa);\n"
"border-radius: 5px;\n"
"}")
        self.iou_slider.setMinimum(1)
        self.iou_slider.setMaximum(100)
        self.iou_slider.setProperty("value", 45)
        self.iou_slider.setOrientation(QtCore.Qt.Horizontal)
        self.iou_slider.setObjectName("iou_slider")
        self.horizontalLayout_16.addWidget(self.iou_slider)
        self.verticalLayout_15.addWidget(self.frame_3)
        self.verticalLayout_22.addWidget(self.IOU_QF)
        self.Conf_QF = QtWidgets.QFrame(self.setting_page)
        self.Conf_QF.setMinimumSize(QtCore.QSize(190, 90))
        self.Conf_QF.setMaximumSize(QtCore.QSize(190, 90))
        self.Conf_QF.setStyleSheet("QFrame#Conf_QF{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.Conf_QF.setObjectName("Conf_QF")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.Conf_QF)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.ToggleBotton_3 = QtWidgets.QPushButton(self.Conf_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton_3.sizePolicy().hasHeightForWidth())
        self.ToggleBotton_3.setSizePolicy(sizePolicy)
        self.ToggleBotton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.ToggleBotton_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        self.ToggleBotton_3.setFont(font)
        self.ToggleBotton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ToggleBotton_3.setMouseTracking(True)
        self.ToggleBotton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton_3.setAutoFillBackground(False)
        self.ToggleBotton_3.setStyleSheet("QPushButton{\n"
"background-image: url(:/setting /images/newsize/conf.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 20px solid transparent;\n"
"\n"
"text-align: left;\n"
"padding-left: 40px;\n"
"padding-bottom: 4px;\n"
"color: white;\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton_3.setIcon(icon)
        self.ToggleBotton_3.setAutoDefault(False)
        self.ToggleBotton_3.setDefault(False)
        self.ToggleBotton_3.setFlat(False)
        self.ToggleBotton_3.setObjectName("ToggleBotton_3")
        self.verticalLayout_18.addWidget(self.ToggleBotton_3)
        self.frame = QtWidgets.QFrame(self.Conf_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 20))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame.setObjectName("frame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_17.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_17.setSpacing(10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.conf_spinbox = QtWidgets.QDoubleSpinBox(self.frame)
        self.conf_spinbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.conf_spinbox.setStyleSheet("QDoubleSpinBox {\n"
"border: 0px solid lightgray;\n"
"border-radius: 2px;\n"
"background-color: rgba(255,255,255,90);\n"
"font: 600 9pt \"Segoe UI\";\n"
"}\n"
"        \n"
"QDoubleSpinBox::up-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/setting /images/newsize/box_up.png);\n"
"}\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top: 1px;\n"
"}\n"
"            \n"
"QDoubleSpinBox::down-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/setting /images/newsize/box_down.png);\n"
"}\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom: 1px;\n"
"}")
        self.conf_spinbox.setMinimum(0.01)
        self.conf_spinbox.setMaximum(1.0)
        self.conf_spinbox.setSingleStep(0.05)
        self.conf_spinbox.setProperty("value", 0.25)
        self.conf_spinbox.setObjectName("conf_spinbox")
        self.horizontalLayout_17.addWidget(self.conf_spinbox)
        self.conf_slider = QtWidgets.QSlider(self.frame)
        self.conf_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.conf_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: none;\n"
"height: 10px;\n"
"background-color: rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 10px;\n"
"margin: -1px 0px -1px 0px;\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #59969b, stop:1 #04e7fa);\n"
"border-radius: 5px;\n"
"}")
        self.conf_slider.setMinimum(1)
        self.conf_slider.setMaximum(100)
        self.conf_slider.setProperty("value", 25)
        self.conf_slider.setOrientation(QtCore.Qt.Horizontal)
        self.conf_slider.setObjectName("conf_slider")
        self.horizontalLayout_17.addWidget(self.conf_slider)
        self.verticalLayout_18.addWidget(self.frame)
        self.verticalLayout_22.addWidget(self.Conf_QF)
        self.Delay_QF = QtWidgets.QFrame(self.setting_page)
        self.Delay_QF.setMinimumSize(QtCore.QSize(190, 90))
        self.Delay_QF.setMaximumSize(QtCore.QSize(190, 90))
        self.Delay_QF.setStyleSheet("QFrame#Delay_QF{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.Delay_QF.setObjectName("Delay_QF")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.Delay_QF)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.ToggleBotton_4 = QtWidgets.QPushButton(self.Delay_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton_4.sizePolicy().hasHeightForWidth())
        self.ToggleBotton_4.setSizePolicy(sizePolicy)
        self.ToggleBotton_4.setMinimumSize(QtCore.QSize(0, 30))
        self.ToggleBotton_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        self.ToggleBotton_4.setFont(font)
        self.ToggleBotton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ToggleBotton_4.setMouseTracking(True)
        self.ToggleBotton_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton_4.setAutoFillBackground(False)
        self.ToggleBotton_4.setStyleSheet("QPushButton{\n"
"background-image:url(:/setting /images/newsize/delay.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 20px solid transparent;\n"
"\n"
"text-align: left;\n"
"padding-left: 40px;\n"
"padding-bottom: 2px;\n"
"color: white;\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton_4.setIcon(icon)
        self.ToggleBotton_4.setAutoDefault(False)
        self.ToggleBotton_4.setDefault(False)
        self.ToggleBotton_4.setFlat(False)
        self.ToggleBotton_4.setObjectName("ToggleBotton_4")
        self.verticalLayout_19.addWidget(self.ToggleBotton_4)
        self.frame_2 = QtWidgets.QFrame(self.Delay_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_18.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_18.setSpacing(10)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.speed_spinbox = QtWidgets.QSpinBox(self.frame_2)
        self.speed_spinbox.setStyleSheet("QSpinBox {\n"
"border: 0px solid lightgray;\n"
"border-radius: 2px;\n"
"background-color: rgba(255,255,255,90);\n"
"font: 600 9pt \"Segoe UI\";\n"
"}\n"
"        \n"
"QSpinBox::up-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/setting /images/newsize/box_up.png);\n"
"}\n"
"QSpinBox::up-button:pressed {\n"
"margin-top: 1px;\n"
"}\n"
"            \n"
"QSpinBox::down-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image:url(:/setting /images/newsize/box_down.png);\n"
"}\n"
"QSpinBox::down-button:pressed {\n"
"margin-bottom: 1px;\n"
"}")
        self.speed_spinbox.setMaximum(50)
        self.speed_spinbox.setProperty("value", 10)
        self.speed_spinbox.setObjectName("speed_spinbox")
        self.horizontalLayout_18.addWidget(self.speed_spinbox)
        self.speed_slider = QtWidgets.QSlider(self.frame_2)
        self.speed_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.speed_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: none;\n"
"height: 10px;\n"
"background-color: rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 10px;\n"
"margin: -1px 0px -1px 0px;\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(253, 139, 133),  stop:1 rgb(248, 194, 152));\n"
"border-radius: 5px;\n"
"}")
        self.speed_slider.setMaximum(50)
        self.speed_slider.setProperty("value", 10)
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setObjectName("speed_slider")
        self.horizontalLayout_18.addWidget(self.speed_slider)
        self.verticalLayout_19.addWidget(self.frame_2)
        self.verticalLayout_22.addWidget(self.Delay_QF)
        self.LINE_THICKNESS = QtWidgets.QFrame(self.setting_page)
        self.LINE_THICKNESS.setMinimumSize(QtCore.QSize(190, 90))
        self.LINE_THICKNESS.setMaximumSize(QtCore.QSize(190, 90))
        self.LINE_THICKNESS.setStyleSheet("QFrame#LINE_THICKNESS{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.LINE_THICKNESS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LINE_THICKNESS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LINE_THICKNESS.setObjectName("LINE_THICKNESS")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.LINE_THICKNESS)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.ToggleBotton_5 = QtWidgets.QPushButton(self.LINE_THICKNESS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton_5.sizePolicy().hasHeightForWidth())
        self.ToggleBotton_5.setSizePolicy(sizePolicy)
        self.ToggleBotton_5.setMinimumSize(QtCore.QSize(0, 30))
        self.ToggleBotton_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        self.ToggleBotton_5.setFont(font)
        self.ToggleBotton_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ToggleBotton_5.setMouseTracking(True)
        self.ToggleBotton_5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton_5.setAutoFillBackground(False)
        self.ToggleBotton_5.setStyleSheet("QPushButton{\n"
"background-image:url(:/setting /images/newsize/line.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 20px solid transparent;\n"
"text-align: left;\n"
"padding-left: 40px;\n"
"padding-bottom: 4px;\n"
"color: white;\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton_5.setIcon(icon)
        self.ToggleBotton_5.setAutoDefault(False)
        self.ToggleBotton_5.setDefault(False)
        self.ToggleBotton_5.setFlat(False)
        self.ToggleBotton_5.setObjectName("ToggleBotton_5")
        self.verticalLayout_23.addWidget(self.ToggleBotton_5)
        self.frame_5 = QtWidgets.QFrame(self.LINE_THICKNESS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_21.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_21.setSpacing(10)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.line_spinbox = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.line_spinbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.line_spinbox.setStyleSheet("QDoubleSpinBox {\n"
"border: 0px solid lightgray;\n"
"border-radius: 2px;\n"
"background-color: rgba(255,255,255,90);\n"
"font: 600 9pt \"Segoe UI\";\n"
"}\n"
"        \n"
"QDoubleSpinBox::up-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/setting /images/newsize/box_up.png);\n"
"}\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top: 1px;\n"
"}\n"
"            \n"
"QDoubleSpinBox::down-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image:url(:/setting /images/newsize/box_down.png);\n"
"}\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom: 1px;\n"
"}")
        self.line_spinbox.setDecimals(0)
        self.line_spinbox.setMinimum(0.0)
        self.line_spinbox.setMaximum(5.0)
        self.line_spinbox.setSingleStep(1.0)
        self.line_spinbox.setProperty("value", 3.0)
        self.line_spinbox.setObjectName("line_spinbox")
        self.horizontalLayout_21.addWidget(self.line_spinbox)
        self.line_slider = QtWidgets.QSlider(self.frame_5)
        self.line_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.line_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: none;\n"
"height: 10px;\n"
"background-color: rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 10px;\n"
"margin: -1px 0px -1px 0px;\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background-color:  qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(253, 139, 133),  stop:1 rgb(248, 194, 152));\n"
"border-radius: 5px;\n"
"}")
        self.line_slider.setMinimum(0)
        self.line_slider.setMaximum(5)
        self.line_slider.setPageStep(1)
        self.line_slider.setProperty("value", 3)
        self.line_slider.setOrientation(QtCore.Qt.Horizontal)
        self.line_slider.setObjectName("line_slider")
        self.horizontalLayout_21.addWidget(self.line_slider)
        self.verticalLayout_23.addWidget(self.frame_5)
        self.verticalLayout_22.addWidget(self.LINE_THICKNESS)
        self.Model_Manage = QtWidgets.QFrame(self.setting_page)
        self.Model_Manage.setMinimumSize(QtCore.QSize(190, 150))
        self.Model_Manage.setStyleSheet("QWidget#Model_Manage{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.Model_Manage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Model_Manage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Model_Manage.setObjectName("Model_Manage")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Model_Manage)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_4 = QtWidgets.QFrame(self.Model_Manage)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(9)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.import_button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_button.sizePolicy().hasHeightForWidth())
        self.import_button.setSizePolicy(sizePolicy)
        self.import_button.setStyleSheet("QPushButton{\n"
"    background-image:url(:/setting /images/newsize/import.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    border: none;    \n"
"    border-left: 10px solid transparent;\n"
"    text-align: left;\n"
"    padding-left: 40px;\n"
"    padding-bottom: 4px;\n"
"    color: white;\n"
"    font: 700 13pt \"Nirmala UI\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.import_button.setObjectName("import_button")
        self.verticalLayout_17.addWidget(self.import_button)
        self.save_status_button = QtWidgets.QCheckBox(self.frame_4)
        self.save_status_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_status_button.setStyleSheet("QCheckBox {\n"
"color: white;\n"
"font: 700 13pt \"Nirmala UI\";\n"
"        }\n"
"QCheckBox::indicator {\n"
"           padding-top: 1px;\n"
"            width: 40px;\n"
"            height: 30px;\n"
"            border: none;\n"
" }\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"            image: url(:/setting /images/newsize/check_no.png);\n"
"        }\n"
"\n"
"QCheckBox::indicator:checked {\n"
"            image:url(:/setting /images/newsize/check_yes.png);\n"
"        }")
        self.save_status_button.setObjectName("save_status_button")
        self.verticalLayout_17.addWidget(self.save_status_button)
        self.save_button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setStyleSheet("QPushButton{\n"
"    background-image:url(:/setting /images/newsize/save.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    border: none;    \n"
"    border-left: 10px solid transparent;\n"
"    text-align: left;\n"
"    padding-left: 40px;\n"
"    padding-bottom: 4px;\n"
"    color: white;\n"
"    font: 700 13pt \"Nirmala UI\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.save_button.setCheckable(False)
        self.save_button.setObjectName("save_button")
        self.verticalLayout_17.addWidget(self.save_button)
        self.verticalLayout_16.addWidget(self.frame_4)
        self.verticalLayout_22.addWidget(self.Model_Manage)
        spacerItem7 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem7)
        self.verticalLayout_6.addWidget(self.setting_page)
        self.mainBox.addWidget(self.settingBox)
        self.verticalLayout_4.addWidget(self.mainbox)
        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(1, 95)
        self.verticalLayout.addWidget(self.mainBody)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.run_button, self.maximizeButton)
        mainWindow.setTabOrder(self.maximizeButton, self.closeButton)
        mainWindow.setTabOrder(self.closeButton, self.minimizeButton)
        mainWindow.setTabOrder(self.minimizeButton, self.stop_button)
        mainWindow.setTabOrder(self.stop_button, self.src_menu)
        mainWindow.setTabOrder(self.src_menu, self.src_img)
        mainWindow.setTabOrder(self.src_img, self.src_camera)
        mainWindow.setTabOrder(self.src_camera, self.src_setting)
        mainWindow.setTabOrder(self.src_setting, self.src_webcam)
        mainWindow.setTabOrder(self.src_webcam, self.src_folder)
        mainWindow.setTabOrder(self.src_folder, self.ToggleBotton_6)
        mainWindow.setTabOrder(self.ToggleBotton_6, self.model_box)
        mainWindow.setTabOrder(self.model_box, self.ToggleBotton_2)
        mainWindow.setTabOrder(self.ToggleBotton_2, self.ToggleBotton_3)
        mainWindow.setTabOrder(self.ToggleBotton_3, self.ToggleBotton_4)
        mainWindow.setTabOrder(self.ToggleBotton_4, self.iou_spinbox)
        mainWindow.setTabOrder(self.iou_spinbox, self.iou_slider)
        mainWindow.setTabOrder(self.iou_slider, self.conf_spinbox)
        mainWindow.setTabOrder(self.conf_spinbox, self.conf_slider)
        mainWindow.setTabOrder(self.conf_slider, self.speed_spinbox)
        mainWindow.setTabOrder(self.speed_spinbox, self.speed_slider)
        mainWindow.setTabOrder(self.speed_slider, self.import_button)
        mainWindow.setTabOrder(self.import_button, self.save_button)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "YOLOSHOW"))
        self.title.setText(_translate("mainWindow", "基于Pyside6的YOLO图像识别用户界面"))
        self.label.setText(_translate("mainWindow", "YOLO SHOW"))
        self.label_3.setText(_translate("mainWindow", "SwimmingLiu"))
        self.src_menu.setText(_translate("mainWindow", " Menu   "))
        self.src_img.setText(_translate("mainWindow", "Media"))
        self.src_webcam.setText(_translate("mainWindow", " Webcam"))
        self.src_folder.setText(_translate("mainWindow", " Folder  "))
        self.src_folder.setShortcut(_translate("mainWindow", "Ctrl+S"))
        self.src_camera.setText(_translate("mainWindow", "Rtsp   "))
        self.src_setting.setText(_translate("mainWindow", "Setting"))
        self.label_5.setText(_translate("mainWindow", "Classes"))
        self.label_6.setText(_translate("mainWindow", "Targets"))
        self.label_7.setText(_translate("mainWindow", "Fps"))
        self.label_8.setText(_translate("mainWindow", "Model"))
        self.message_bar.setText(_translate("mainWindow", "Message Bar ... "))
        self.label_2.setText(_translate("mainWindow", "Settings"))
        self.ToggleBotton_6.setText(_translate("mainWindow", "Model"))
        self.ToggleBotton_2.setText(_translate("mainWindow", "IOU"))
        self.ToggleBotton_3.setText(_translate("mainWindow", "Confidence"))
        self.ToggleBotton_4.setText(_translate("mainWindow", "Delay(ms)"))
        self.ToggleBotton_5.setText(_translate("mainWindow", "Line Width"))
        self.import_button.setText(_translate("mainWindow", "Import Model"))
        self.save_status_button.setText(_translate("mainWindow", "Save MP4/JPG"))
        self.save_button.setText(_translate("mainWindow", "Save Result"))
from qfluentwidgets import ComboBox
from ui.UpdateFrame import DoubleClickQFrame
import YOLOSHOWUI_rc
